#!/usr/bin/env sh

show_help() {
cat <<'HELP'
Usage: su [-c COMMAND]

Execute shell or command.

Options:
  -c COMMAND   run command
  -h           display help
HELP
}

cmd=""

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;

    -c)
      shift
      cmd="$1"
      shift
      ;;

    *)
      shift
      ;;
  esac
done

if [ -n "$cmd" ]; then
  exec bash -c "$cmd"
fi

exec bash
